In [38]:
import pandas as pd
import numpy as np
import numpy_financial as npf

In [19]:
from pathlib import Path

In [9]:
Path.cwd()

WindowsPath('C:/Users/jayri/GitHub/python-homework/PyBank')

In [26]:
PnL = pd.read_csv('C:/Users/jayri/GitHub/python-homework/PyBank/week_2_homework_PyBank_Resources_budget_data.csv')
print (PnL)

        Date  Profit/Losses
0   Jan-2010         867884
1   Feb-2010         984655
2   Mar-2010         322013
3   Apr-2010         -69417
4   May-2010         310503
..       ...            ...
81  Oct-2016         102685
82  Nov-2016         795914
83  Dec-2016          60988
84  Jan-2017         138230
85  Feb-2017         671099

[86 rows x 2 columns]


In [29]:
print(PnL.columns)

Index(['Date', 'Profit/Losses'], dtype='object')


In [31]:
print(PnL['Date'])

0     Jan-2010
1     Feb-2010
2     Mar-2010
3     Apr-2010
4     May-2010
        ...   
81    Oct-2016
82    Nov-2016
83    Dec-2016
84    Jan-2017
85    Feb-2017
Name: Date, Length: 86, dtype: object


In [44]:
total_months = len(PnL['Date'])
print (total_months)

86


In [43]:
net_total = sum(PnL['Profit/Losses'])
print (net_total)

38382578


In [51]:
average_changes = net_total / total_months
print (average_changes)

446309.0465116279


In [53]:
greatest_increase = max(PnL["Profit/Losses"])
print (greatest_increase)

1170593


In [61]:
PnL_Monthly_List = [(PnL['Profit/Losses'])]
print (PnL_Monthly_List)

[0     867884
1     984655
2     322013
3     -69417
4     310503
       ...  
81    102685
82    795914
83     60988
84    138230
85    671099
Name: Profit/Losses, Length: 86, dtype: int64]


In [63]:
PnL_Date_List = PnL['Date']

In [180]:
np.diff (PnL_Monthly_List)

array([[  116771,  -662642,  -391430,   379920,   212354,   510239,
         -428211,  -821271,   693918,   416278,  -974163,   860159,
        -1115009,  1033048,    95318,  -308093,    99052,  -521393,
          605450,   231727,   -65187,  -702716,   177975, -1065544,
         1926159,  -917805,   898730,  -334262,  -246499,   -64055,
        -1529236,  1497596,   304914,  -635801,   398319,  -183161,
          -37864,  -253689,   403655,    94168,   306877,   -83000,
          210462, -2196167,  1465222,  -956983,  1838447,  -468003,
          -64602,   206242,  -242155,  -449079,   315198,   241099,
          111540,   365942,  -219310,  -368665,   409837,   151210,
         -110244,  -341938, -1212159,   683246,   -70825,   335594,
          417334,  -272194,  -236462,   657432,  -211262,  -128237,
        -1750387,   925441,   932089,  -311434,   267252, -1876758,
         1733696,   198551,  -665765,   693229,  -734926,    77242,
          532869]], dtype=int64)

In [181]:
superman = np.diff (PnL_Monthly_List)

In [182]:
for numbers in (superman):
    megaman = sum (numbers)

In [186]:
ironman = megaman / (total_months -1)

In [190]:
round (ironman,2)

-2315.12

In [192]:
np.diff (PnL['Profit/Losses'])

array([  116771,  -662642,  -391430,   379920,   212354,   510239,
        -428211,  -821271,   693918,   416278,  -974163,   860159,
       -1115009,  1033048,    95318,  -308093,    99052,  -521393,
         605450,   231727,   -65187,  -702716,   177975, -1065544,
        1926159,  -917805,   898730,  -334262,  -246499,   -64055,
       -1529236,  1497596,   304914,  -635801,   398319,  -183161,
         -37864,  -253689,   403655,    94168,   306877,   -83000,
         210462, -2196167,  1465222,  -956983,  1838447,  -468003,
         -64602,   206242,  -242155,  -449079,   315198,   241099,
         111540,   365942,  -219310,  -368665,   409837,   151210,
        -110244,  -341938, -1212159,   683246,   -70825,   335594,
         417334,  -272194,  -236462,   657432,  -211262,  -128237,
       -1750387,   925441,   932089,  -311434,   267252, -1876758,
        1733696,   198551,  -665765,   693229,  -734926,    77242,
         532869], dtype=int64)

In [193]:
asdasd = []

In [222]:
asdasd.append (superman)

In [223]:
asdasd

[0     Jan-2010
 1     Feb-2010
 2     Mar-2010
 3     Apr-2010
 4     May-2010
         ...   
 81    Oct-2016
 82    Nov-2016
 83    Dec-2016
 84    Jan-2017
 85    Feb-2017
 Name: Date, Length: 86, dtype: object,
 array([[  116771,  -662642,  -391430,   379920,   212354,   510239,
          -428211,  -821271,   693918,   416278,  -974163,   860159,
         -1115009,  1033048,    95318,  -308093,    99052,  -521393,
           605450,   231727,   -65187,  -702716,   177975, -1065544,
          1926159,  -917805,   898730,  -334262,  -246499,   -64055,
         -1529236,  1497596,   304914,  -635801,   398319,  -183161,
           -37864,  -253689,   403655,    94168,   306877,   -83000,
           210462, -2196167,  1465222,  -956983,  1838447,  -468003,
           -64602,   206242,  -242155,  -449079,   315198,   241099,
           111540,   365942,  -219310,  -368665,   409837,   151210,
          -110244,  -341938, -1212159,   683246,   -70825,   335594,
           417334,  -2721

In [195]:
print (asdasd)

[0     Jan-2010
1     Feb-2010
2     Mar-2010
3     Apr-2010
4     May-2010
        ...   
81    Oct-2016
82    Nov-2016
83    Dec-2016
84    Jan-2017
85    Feb-2017
Name: Date, Length: 86, dtype: object]


In [224]:
micky = []

In [225]:
micky.append (superman)

In [226]:
micky.insert (0,0)

In [227]:
micky

[0,
 array([[  116771,  -662642,  -391430,   379920,   212354,   510239,
          -428211,  -821271,   693918,   416278,  -974163,   860159,
         -1115009,  1033048,    95318,  -308093,    99052,  -521393,
           605450,   231727,   -65187,  -702716,   177975, -1065544,
          1926159,  -917805,   898730,  -334262,  -246499,   -64055,
         -1529236,  1497596,   304914,  -635801,   398319,  -183161,
           -37864,  -253689,   403655,    94168,   306877,   -83000,
           210462, -2196167,  1465222,  -956983,  1838447,  -468003,
           -64602,   206242,  -242155,  -449079,   315198,   241099,
           111540,   365942,  -219310,  -368665,   409837,   151210,
          -110244,  -341938, -1212159,   683246,   -70825,   335594,
           417334,  -272194,  -236462,   657432,  -211262,  -128237,
         -1750387,   925441,   932089,  -311434,   267252, -1876758,
          1733696,   198551,  -665765,   693229,  -734926,    77242,
           532869]], dtype=int

In [197]:
sonic = pd.DataFrame ()

In [200]:
sonic['Date'] = (PnL['Date'])

In [229]:
sonic [micky] = [micky]

TypeError: unhashable type: 'numpy.ndarray'

In [215]:
sonic

Date  116771  -662642  -391430  379920  212354  510239  -428211  \
0   Jan-2010  116771  -662642  -391430  379920  212354  510239  -428211   
1   Feb-2010  116771  -662642  -391430  379920  212354  510239  -428211   
2   Mar-2010  116771  -662642  -391430  379920  212354  510239  -428211   
3   Apr-2010  116771  -662642  -391430  379920  212354  510239  -428211   
4   May-2010  116771  -662642  -391430  379920  212354  510239  -428211   
..       ...     ...      ...      ...     ...     ...     ...      ...   
81  Oct-2016  116771  -662642  -391430  379920  212354  510239  -428211   
82  Nov-2016  116771  -662642  -391430  379920  212354  510239  -428211   
83  Dec-2016  116771  -662642  -391430  379920  212354  510239  -428211   
84  Jan-2017  116771  -662642  -391430  379920  212354  510239  -428211   
85  Feb-2017  116771  -662642  -391430  379920  212354  510239  -428211   

    -821271  693918  ...  445709  712961  -1163797  569899  768450  102685  \
0   -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   
1   -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   
2   -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   
3   -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   
4   -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   
..      ...     ...  ...     ...     ...       ...     ...     ...     ...   
81  -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   
82  -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   
83  -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   
84  -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   
85  -821271  693918  ...     NaN     NaN       NaN     NaN     NaN     NaN   

    795914  60988  138230  671099  
0      NaN    NaN     NaN     NaN  
1      NaN    NaN     NaN     NaN  
2      NaN    NaN     NaN     NaN  
3      NaN    NaN     NaN     NaN  
4      NaN    NaN     NaN     NaN  
..     ...    ...     ...     ...  
81     NaN    NaN     NaN     NaN  
82     NaN    NaN     NaN     NaN  
83     NaN    NaN     NaN     NaN  
84     NaN    NaN     NaN     NaN  
85     NaN    NaN     NaN     NaN  

[86 rows x 172 columns]